### ISSUE TITLE
AttributeError: 'int' object has no attribute 'session'

### ISSUE THREAD

**Issue by bendog** [flavors/django-graphql-jwt#113]
While I've got graphql_jwt in Graphene['Middleware'] I can't get any response from the GraphiQL interface or load the Schema.

However, if I provide the JWT it does work.

I am running a custom `JWT_DECODE_HANDLER` script to Authenticate against AWS Cognito.

settings.py
```python
GRAPHENE = {
    'SCHEMA': 'rfid.schema.schema',
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ],
}
```

graphql error
```json
{
  "errors": [
    {
      "message": "'int' object has no attribute 'session'",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "__schema"
      ]
    }
  ],
  "data": null
}
```

Django error message
```
"GET /graphql HTTP/1.1" 200 1285
An error occurred while resolving field Query.__schema
Traceback (most recent call last):
  File "$PROJDIR.venv/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "$PROJDIR.venv/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "$PROJDIR.venv/lib/python3.7/site-packages/graphql_jwt/middleware.py", line 112, in resolve
    if ((_authenticate(context) or token_argument is not None) and
  File "$PROJDIR.venv/lib/python3.7/site-packages/graphql_jwt/middleware.py", line 39, in _authenticate
    is_anonymous = not hasattr(request, 'user') or request.user.is_anonymous
  File "$PROJDIR.venv/lib/python3.7/site-packages/django/utils/functional.py", line 256, in inner
    self._setup()
  File "$PROJDIR.venv/lib/python3.7/site-packages/django/utils/functional.py", line 392, in _setup
    self._wrapped = self._setupfunc()
  File "$PROJDIR.venv/lib/python3.7/site-packages/django/contrib/auth/middleware.py", line 24, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "$PROJDIR.venv/lib/python3.7/site-packages/django/contrib/auth/middleware.py", line 12, in get_user
    request._cached_user = auth.get_user(request)
  File "$PROJDIR.venv/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 189, in get_user
    user = get_user(user_id)
  File "$PROJDIR.venv/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 182, in get_user
    user_id = _get_user_session_key(request)
  File "$PROJDIR.venv/lib/python3.7/site-packages/django/contrib/auth/__init__.py", line 59, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
```

**Comment by mongkok** [comment]
Hi @bendog, any updates?

**Comment by bendog** [comment]
@mongkok I'm not working on the project i was using this for anymore, so I can't see how i resolved it, if i even did...

**Comment by jackton1** [comment]
@mongkok @bendog I think the problem here is with this line

```py
'JWT_PAYLOAD_GET_USERNAME_HANDLER': lambda payload: payload.get('sub'),
```

Guessing you used [auth0](https://auth0.com/blog/building-modern-applications-with-django-and-vuejs/) which returns an id so you need to update the `JWT_GET_USER_BY_NATURAL_KEY_HANDLER` to handle retrieving the user by id.
