### ISSUE TITLE
Error on wrapping GraphQLView.as_view with login_required decorator

### ISSUE THREAD

**Issue by charl3sj** [flavors/django-graphql-jwt#139]
I am trying to setup a private GraphQL endpoint like so:
```
urlpatterns += [
    ....
    path('graphql-staff', login_required(GraphQLView.as_view(schema=private_schema, graphiql=True)))
]
```

However, when I try to query that endpoint, I get the following error:
```
ERROR 2019-10-05 13:31:16,991 log 63362 123145503166464 Internal Server Error: /graphql-staff
Traceback (most recent call last):
  File "/Users/.../lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Users/.../lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/.../lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/Users/.../lib/python3.7/site-packages/graphql_jwt/decorators.py", line 30, in wrapper
    info = next(arg for arg in args if isinstance(arg, ResolveInfo))
StopIteration
```

Settings:
```
GRAPHENE = {
    'MIDDLEWARE': [
        'graphql_jwt.middleware.JSONWebTokenMiddleware',
    ]
}

GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=1),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(minutes=5),
}
```

I'm not sure how to go about fixing this... any pointers would be appreciated!

**Comment by charl3sj** [comment]
Looks like the decorators require the info object to be set to work.

I ended up modifying `JSONWebTokenAuthMixin` from https://github.com/jpadilla/django-jwt-auth/blob/master/jwt_auth/mixins.py to play well with `django-graphql-jwt` since both use `PyJWT`, subclassed it into a view and used that in my urlconf.

The view:
```
from utils.jwt_auth import JSONWebTokenAuthMixin

class StaffGraphQLView(JSONWebTokenAuthMixin, GraphQLView):
    pass
```

URLconf:
```
urlpatterns = [
    ...
    path('<path>', StaffGraphQLView.as_view(schema=private_schema)),
]
```
