### ISSUE TITLE
tokenAuth can't be executed by graphene.Schema

### ISSUE THREAD

**Issue by CSFlorin** [flavors/django-graphql-jwt#183]
I have a schema like:
```
class Mutation(backend.app.schema.Mutation, graphene.ObjectType):
    token_auth = graphql_jwt.relay.ObtainJSONWebToken.Field()

schema = graphene.Schema(mutation=Mutation)
```
And I want to generate an auth token for my tests using something like the following in a test class that inherits from `django.test.testcases.TestCase`
```
schema.execute(
"""
mutation TokenAuth($input: ObtainJSONWebTokenInput!) {
    tokenAuth(input: $input) {
        token
    }
}
""",
variables={"input": {"username": "user1", "password": "password"}}
)
```
However, executing that gives
```
An error occurred while resolving field Mutation.tokenAuth
Traceback (most recent call last):
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphene/relay/mutation.py", line 70, in mutate
    result = cls.mutate_and_get_payload(root, info, **input)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 110, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 70, in wrapper
    context._jwt_token_auth = True
AttributeError: 'NoneType' object has no attribute '_jwt_token_auth'
Traceback (most recent call last):
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql/execution/executor.py", line 452, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql/execution/executors/sync.py", line 16, in execute
    return fn(*args, **kwargs)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphene/relay/mutation.py", line 70, in mutate
    result = cls.mutate_and_get_payload(root, info, **input)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 110, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/Users/f/tf-web/env/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 70, in wrapper
    context._jwt_token_auth = True
graphql.error.located_error.GraphQLLocatedError: 'NoneType' object has no attribute '_jwt_token_auth'

[GraphQLLocatedError("'NoneType' object has no attribute '_jwt_token_auth'",)]
```

Everything works fine if I send this as a request to my server's graphql endpoint, so I don't know what's going wrong.

**Comment by mongkok** [comment]
Hi @CSFlorin ,
You can use the [JSONWebTokenTestCase](https://django-graphql-jwt.domake.io/en/latest/tests.html) for tests,
this class injects a request/context object into the schema execution.

I close the issue, if you have any questions please let me know.

**Comment by royroy21** [comment]
What options do we have if I use pytest?
