### ISSUE TITLE
No installed app with label 'refresh_token'

### ISSUE THREAD

**Issue by art-zhitnik** [flavors/django-graphql-jwt#187]
Trying to make authentication on 0.3.1 (python 3.6.8, django 2.1):
```graphql
mutation ($username: String!, $password: String!) {
  tokenAuth(username: $username, password: $password) {
    token
  }
}
```
Got error:
```graphql
{
  "errors": [
    {
      "message": "No installed app with label 'refresh_token'.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "tokenAuth"
      ]
    }
  ],
  "data": {
    "tokenAuth": null
  }
}
```

**Comment by art-zhitnik** [comment]
The error was:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 489, in _resolve_from_executor
    executor(resolve, reject)
  File "/usr/local/lib/python3.6/site-packages/promise/promise.py", line 756, in executor
    return resolve(f(*args, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/graphql/execution/middleware.py", line 75, in make_it_promise
    return next(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 140, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 129, in wrapper
    result = f(cls, root, info, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 121, in wrapper
    result = f(cls, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 107, in wrapper
    return maybe_thenable((context, user, result), on_token_auth_resolve)
  File "/usr/local/lib/python3.6/site-packages/graphene/utils/thenables.py", line 42, in maybe_thenable
    return on_resolve(obj)
  File "/usr/local/lib/python3.6/site-packages/graphql_jwt/decorators.py", line 74, in on_token_auth_resolve
    context.jwt_refresh_token = create_refresh_token(user)
  File "/usr/local/lib/python3.6/site-packages/graphql_jwt/refresh_token/shortcuts.py", line 27, in create_refresh_token
    return get_refresh_token_model().objects.create(user=user)
  File "/usr/local/lib/python3.6/site-packages/graphql_jwt/refresh_token/utils.py", line 7, in get_refresh_token_model
    return apps.get_model(jwt_settings.JWT_REFRESH_TOKEN_MODEL)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 202, in get_model
    app_config = self.get_app_config(app_label)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 159, in get_app_config
    raise LookupError(message)
graphql.error.located_error.GraphQLLocatedError: No installed app with label 'refresh_token'.
```

**Comment by TitanFighter** [comment]
Did you try [change settings](https://django-graphql-jwt.domake.io/en/latest/refresh_token.html#long-running-refresh-tokens)?

**Comment by art-zhitnik** [comment]
I use settings from docs:
```python
GRAPHQL_JWT = {
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LONG_RUNNING_REFRESH_TOKEN': True,
    'JWT_EXPIRATION_DELTA': timedelta(minutes=5),
    'JWT_REFRESH_EXPIRATION_DELTA': timedelta(days=7),
}
```

**Comment by TitanFighter** [comment]
I am talking about this one:
```
INSTALLED_APPS = [
    ...
    'graphql_jwt.refresh_token.apps.RefreshTokenConfig',
    ...
]
```
Did you add it?

**Comment by art-zhitnik** [comment]
That's it! I added the line to INSTALLED_APPS, made migration and now it works! Thank you!
