### ISSUE TITLE
Does it really support Graphene V3 ?

### ISSUE THREAD

**Issue by laurent-brisbois** [flavors/django-graphql-jwt#250]
Hello everyone !

According to [this commit](https://github.com/flavors/django-graphql-jwt/commit/d50a533e26f1509828ef9fc804b195ebdfc1c04e), Graphene V3 should be supported.
However if I use :
```
django==3.1.5
psycopg2==2.8.6
graphene-django==3.0.0b7
django-graphql-jwt==0.3.1
PyJWT>=1.5.0,<2
pyyaml==5.3.1
gunicorn==20.0.4
```
as requirements, I have errors :
```
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run      
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\utils\autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\django\core\management\commands\runserver.py", line 118, in inner_run
    self.check(display_num_errors=True)
  File "C:\Program Files\Python37\lib\site-packages\django\core\management\base.py", line 396, in check
    databases=databases,
  File "C:\Program Files\Python37\lib\site-packages\django\core\checks\registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)       
  File "C:\Program Files\Python37\lib\site-packages\django\core\checks\urls.py", line 40, in check_url_namespaces_unique
    all_namespaces = _load_all_namespaces(resolver)
  File "C:\Program Files\Python37\lib\site-packages\django\core\checks\urls.py", line 57, in _load_all_namespaces
    url_patterns = getattr(resolver, 'url_patterns', [])
  File "C:\Program Files\Python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Program Files\Python37\lib\site-packages\django\urls\resolvers.py", line 589, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Program Files\Python37\lib\site-packages\django\utils\functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Program Files\Python37\lib\site-packages\django\urls\resolvers.py", line 582, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in 
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load        
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked        
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module  
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "E:\Documents\Projects\myproject\myproject\backend\urls.py", line 22, in <module>
    from graphql_jwt.decorators import jwt_cookie
  File "C:\Program Files\Python37\lib\site-packages\graphql_jwt\__init__.py", line 1, in <module>
    from . import relay
  File "C:\Program Files\Python37\lib\site-packages\graphql_jwt\relay.py", 
line 5, in <module>
    from . import mixins
  File "C:\Program Files\Python37\lib\site-packages\graphql_jwt\mixins.py", line 8, in <module>
    from .decorators import csrf_rotation, ensure_token, setup_jwt_cookie  
  File "C:\Program Files\Python37\lib\site-packages\graphql_jwt\decorators.py", line 10, in <module>
    from graphql.execution.base import ResolveInfo
ModuleNotFoundError: No module named 'graphql.execution.base'
```

**Comment by laurent-brisbois** [comment]
> It doesn't 🙂 graphene-django v3 is still in beta phase and no perfect integration is expected at the moment. Apart from that, this package has a lot of issues at the moment and suffers from lack of maintenance. It will be forked soon.

Indeed. Unfortunately I have this feeling for every graphql-python related package... There are issues like graphene-django V2 doesn't support `null` values sent from frontend. It is supposed to be fixed in graphene V3 but I don't know if it will be released one day...

I think more and more about switching to django-rest-framework which seems to be way more maintained.. Even if I have to lose the benefits of graphql. I can't imagine waiting months and months for fixes that are not minor at all.

**Comment by ulgens** [comment]
I agree with you completely and i can enhance those bad examples, but it in the end all of that depends on unpaid labor and I'm trying to contribute related packages as much as possible :slightly_smiling_face:

**Comment by laurent-brisbois** [comment]
> But in the end, all of that depends on unpaid labour and I'm trying to contribute on related packages as much as possible 🙂

Ye I know :-( I would like to have the time to do so but unfortunately it isn't the case. Maybe when my project will be lucrative enough and I'll have employees we'll be able to dedicate some time to used libraries :P
