### ISSUE TITLE
After adding refresh token app into INSTALLED_APPS got an error

### ISSUE THREAD

**Issue by pythoneast** [flavors/django-graphql-jwt#79]
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x1111257b8>
Traceback (most recent call last):
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/contrib/auth/checks.py", line 74, in check_user_model
    if isinstance(cls().is_anonymous, MethodType):
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/db/models/base.py", line 470, in __init__
    _setattr(self, field.attname, val)
  File "/Users/pythoneast/Desktop/work/CHOCOLIFE/choco_projects/market/venv/lib/python3.6/site-packages/django/db/models/fields/related_descriptors.py", line 537, in __set__
    % self._get_set_deprecation_msg_params(),
TypeError: Direct assignment to the reverse side of a related set is prohibited. Use refresh_token.set() instead.
```

**Comment by mongkok** [comment]
Hi @pythoneast ,
you may have a `refresh_token` field in your custom user model.
I have renamed the `RefreshToken.user.related_name` to `refresh_tokens` PR #80.
